//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSolRepo.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HotelDBEntities : DbContext
    {
        public HotelDBEntities()
            : base("name=HotelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Habitaciones> Habitaciones { get; set; }
        public virtual DbSet<HabitacionesDobles> HabitacionesDobles { get; set; }
        public virtual DbSet<HabitacionesSencillas> HabitacionesSencillas { get; set; }
        public virtual DbSet<HabitacionesSuite> HabitacionesSuite { get; set; }
        public virtual DbSet<ProgramasFidelizacion> ProgramasFidelizacion { get; set; }
        public virtual DbSet<ReservaHabitaciones> ReservaHabitaciones { get; set; }
        public virtual DbSet<Reservas> Reservas { get; set; }
        public virtual DbSet<TareasEmpleados> TareasEmpleados { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
    
        public virtual int sp_RealizarCheckIn(Nullable<int> reservaID)
        {
            var reservaIDParameter = reservaID.HasValue ?
                new ObjectParameter("ReservaID", reservaID) :
                new ObjectParameter("ReservaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RealizarCheckIn", reservaIDParameter);
        }
    
        public virtual int sp_RealizarCheckOut(Nullable<int> reservaID)
        {
            var reservaIDParameter = reservaID.HasValue ?
                new ObjectParameter("ReservaID", reservaID) :
                new ObjectParameter("ReservaID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RealizarCheckOut", reservaIDParameter);
        }
    }
}
