//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSolRepo.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public string NIF { get; set; }
        public string Empresa { get; set; }
        public string Contacto { get; set; }
        public string CorreoElectronico { get; set; }
        public string TipoProveedor { get; set; }
        public string CondicionesDePago { get; set; }
        public Nullable<int> DireccionID { get; set; }
    
        public virtual Direcciones Direcciones { get; set; }
    }
}
