
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelSolRepo.Modelo
{

using System;
    using System.Collections.Generic;
    
public partial class Reservas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Reservas()
    {

        this.ReservaHabitaciones = new HashSet<ReservaHabitaciones>();

    }


    public int ReservaID { get; set; }

    public string NIF { get; set; }

    public Nullable<int> HabitacionID { get; set; }

    public Nullable<int> EmpleadoID { get; set; }

    public Nullable<System.DateTime> FechaInicio { get; set; }

    public Nullable<System.DateTime> FechaFin { get; set; }

    public string OpcionesPension { get; set; }

    public string Estado { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string TipoReserva { get; set; }



    public virtual Clientes Clientes { get; set; }

    public virtual Empleados Empleados { get; set; }

    public virtual Habitaciones Habitaciones { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ReservaHabitaciones> ReservaHabitaciones { get; set; }

}

}
