USE [master]
GO

/****** Object:  Database [HotelDB]    Script Date: 26/10/2023 12:04:03 ******/
CREATE DATABASE [HotelDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelDB', FILENAME = N'G:\SQLdata\HotelDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HotelDB_log', FILENAME = N'G:\SQLdata\HotelDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotelDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotelDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotelDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotelDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotelDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotelDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [HotelDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotelDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotelDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotelDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotelDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotelDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotelDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotelDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotelDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HotelDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotelDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotelDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotelDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotelDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotelDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotelDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotelDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HotelDB] SET  MULTI_USER 
GO

ALTER DATABASE [HotelDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotelDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HotelDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HotelDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HotelDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HotelDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HotelDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [HotelDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [HotelDB] SET  READ_WRITE 
GO

