//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSolRepo.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int ReservaID { get; set; }
        public string NIF { get; set; }
        public Nullable<int> HabitacionID { get; set; }
        public Nullable<int> EmpleadoID { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string OpcionesPension { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string TipoReserva { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Habitaciones Habitaciones { get; set; }
    }
}
