using HotelSolRepo.Modelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HotelSolRepo.Controlador
{
    /*
  Este es el modelo 
 //------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSolRepo.Modelo
{
using System;
using System.Collections.Generic;

public partial class Incidencias
{
 public int IncidenciaID { get; set; }
 public string Descripcion { get; set; }
 public System.DateTime FechaReporte { get; set; }
 public Nullable<int> HabitacionID { get; set; }

 public virtual Habitaciones Habitaciones { get; set; }
}
}

  */
    public class IncidenciaController
    {
        // Metodo Para registrar una incidencia
 
        public bool RegistrarIncidencia(int habitacionID, string mensaje)
        {
            using (HotelDBEntities db = new HotelDBEntities())
            {
                var incidencia = new Incidencias()
                {
                    Descripcion = mensaje,
                    FechaReporte = DateTime.Now,
                    HabitacionID = habitacionID
                };
                db.Incidencias.Add(incidencia);
                db.SaveChanges();
                return true;
            }
        }
        // Metodo para modificar una incidencia
        public bool ModificarIncidencia(int incidenciaID, int habitacionID, string mensaje)
        {
            using (HotelDBEntities db = new HotelDBEntities())
            {
                var incidencia = db.Incidencias.FirstOrDefault(i => i.IncidenciaID == incidenciaID);
                incidencia.HabitacionID = habitacionID;
                incidencia.Descripcion = mensaje;
                db.SaveChanges();
                return true;
            }
        }
        // Metodo para eliminar una incidencia
        public bool EliminarIncidencia(int incidenciaID)
        {
            using (HotelDBEntities db = new HotelDBEntities())
            {
                var incidencia = db.Incidencias.FirstOrDefault(i => i.IncidenciaID == incidenciaID);
                db.Incidencias.Remove(incidencia);
                db.SaveChanges();
                return true;
            }
        }
        // Metodo para obtener una incidencia
        public Incidencias ObtenerIncidencia(int incidenciaID)
        {
            using (HotelDBEntities db = new HotelDBEntities())
            {
                var incidencia = db.Incidencias.FirstOrDefault(i => i.IncidenciaID == incidenciaID);
                return incidencia;
            }
        }
        // Metodo para obtener todas las incidencias
        public List<Incidencias> ObtenerIncidencias()
        {
            using (HotelDBEntities db = new HotelDBEntities())
            {
                var incidencias = db.Incidencias.ToList();
                return incidencias;
            }
        }
    }
}
